server:
  port: 8091

spring:
  application:
    name: starshipw2m-api
  security:
    user:
      name: user
      password: 123456
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  # RabbitMQ Configuration
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s  # Espera 10s antes de fallar la conexión
  cache:
    type: redis
  redis:
    host: redis
    port: 6379
    timeout: 5000ms
    connection-timeout: 10s  # Espera 10s antes de fallar la conexión


rabbitmq:
  # RabbitMQ Custom Properties
  queue:
    name: starship.queue
  exchange:
    name: starship.exchange
  routing:
    key: starship.routing.key

  #datasource:
  #  url: jdbc:h2:mem:starshipdb
  #  username: sa
  #  password: password
  #  driverClassName: org.h2.Driver
  #jpa:
  #  database-platform: org.hibernate.dialect.H2Dialect
  #  hibernate:
  #    ddl-auto: none

logging:
  level:
    root: INFO